### ISSUE TITLE
Page Happy Hour

### ISSUE THREAD

**Issue by ElvisBM** [Amarelo-Manga/don-cordero#4]
- Banner Chopp com um P só
- Centralizar o texto na Altura
- Galeria Fotos de Bebidas

**Comment by walacefex** [comment]
Alteração foram feitas do banner
Altura do texto foi alterado para mozila
Galeria alterada.
![screen shot 2018-01-11 at 16 19 20](https://user-images.githubusercontent.com/16948390/34840194-640ecdd0-f6eb-11e7-90f6-595651e65651.png)
