### ISSUE TITLE
Page Cozinha

### ISSUE THREAD

**Issue by ElvisBM** [Amarelo-Manga/don-cordero#7]
- Quebra de Linhas

**Comment by ElvisBM** [comment]
Tirar a 4 foto do carrosel

**Comment by walacefex** [comment]
A quebra de linhas foi resolvida e a quarta foto retirada.

![screen shot 2018-01-11 at 14 35 27](https://user-images.githubusercontent.com/16948390/34835699-b6cadaaa-f6dc-11e7-9b55-cfdc8ff44250.png)
